// Demo orders shown in the admin dashboard before Supabase is connected.
// Replace entirely once real orders come from the DB.

import { Order } from './supabase';

export const DEMO_ORDERS: Order[] = [
  {
    id: 'demo-1', order_num: 'IH-481203', status: 'pending',
    customer_name: 'أميرة بن علي', phone: '0555123456',
    wilaya: 'الجزائر', commune: 'حيدرة', address: '12 شارع الأمير عبد القادر',
    delivery_type: 'home', product_id: 1,
    product_name: 'فولار حرير ناعم — كلاسيك', product_emoji: '🧣',
    color_index: 0, size: 'M', qty: 2,
    subtotal: 3600, delivery_price: 600, discount: 0, promo_code: null, total: 4200,
    notes: null, items: null, stock_deducted: false, created_at: new Date(Date.now() - 3600000).toISOString(), updated_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'demo-2', order_num: 'IH-571044', status: 'confirmed',
    customer_name: 'رنا مزيان', phone: '0661987654',
    wilaya: 'وهران', commune: 'وهران', address: '5 شارع لاربي بن مهيدي',
    delivery_type: 'home', product_id: 3,
    product_name: 'عباية إحسان الكلاسيكية', product_emoji: '👗',
    color_index: 1, size: 'L', qty: 1,
    subtotal: 4200, delivery_price: 600, discount: 420, promo_code: 'IHSEN10', total: 4380,
    notes: "أريد اللون الأسود", items: null, stock_deducted: false, created_at: new Date(Date.now() - 7200000).toISOString(), updated_at: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'demo-3', order_num: 'IH-392817', status: 'shipped',
    customer_name: 'سارة خالدي', phone: '0770456123',
    wilaya: 'قسنطينة', commune: 'عين الباي', address: 'حي الأمير',
    delivery_type: 'office', product_id: 7,
    product_name: 'عباية مطرزة — إحسان ليمتد', product_emoji: '👗',
    color_index: 0, size: 'XL', qty: 1,
    subtotal: 6500, delivery_price: 0, discount: 0, promo_code: 'FREESHIP', total: 6500,
    notes: null, items: null, stock_deducted: false, created_at: new Date(Date.now() - 86400000).toISOString(), updated_at: new Date(Date.now() - 43200000).toISOString(),
  },
  {
    id: 'demo-4', order_num: 'IH-204561', status: 'delivered',
    customer_name: 'نور الهدى بوعزيز', phone: '0551234000',
    wilaya: 'عنابة', commune: 'عنابة', address: 'شارع 1 نوفمبر',
    delivery_type: 'home', product_id: 4,
    product_name: 'هودي قطن دافئ — ذهبي', product_emoji: '🧥',
    color_index: 0, size: 'S', qty: 1,
    subtotal: 2900, delivery_price: 600, discount: 500, promo_code: 'WELCOME', total: 3000,
    notes: null, items: null, stock_deducted: false, created_at: new Date(Date.now() - 172800000).toISOString(), updated_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'demo-5', order_num: 'IH-103928', status: 'reviewing',
    customer_name: 'فاطمة الزهراء', phone: '0662780011',
    wilaya: 'تيزي وزو', commune: 'أث يرزر', address: 'قرية آث يرزر',
    delivery_type: 'home', product_id: 2,
    product_name: 'حجاب شيفون خفيف — ربيعي', product_emoji: '🧕',
    color_index: 2, size: 'M', qty: 3,
    subtotal: 4500, delivery_price: 600, discount: 0, promo_code: null, total: 5100,
    notes: "ألوان مختلفة للـ 3 قطع", items: null, stock_deducted: false, created_at: new Date(Date.now() - 1800000).toISOString(), updated_at: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'demo-6', order_num: 'IH-887234', status: 'attempt_failed',
    customer_name: 'ليلى حمدوش', phone: '0555901234',
    wilaya: 'سطيف', commune: 'سطيف', address: '7 حي النصر',
    delivery_type: 'home', product_id: 6,
    product_name: 'حجاب مخمل فاخر — شتوي', product_emoji: '🧕',
    color_index: 1, size: 'L', qty: 1,
    subtotal: 1800, delivery_price: 600, discount: 0, promo_code: null, total: 2400,
    notes: null, items: null, stock_deducted: false, created_at: new Date(Date.now() - 259200000).toISOString(), updated_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'demo-7', order_num: 'IH-665102', status: 'returned',
    customer_name: 'هاجر مسعودي', phone: '0770123890',
    wilaya: 'بسكرة', commune: 'بسكرة', address: 'شارع العربي بن مهيدي',
    delivery_type: 'home', product_id: 8,
    product_name: 'هودي محتشم طويل — زيتي', product_emoji: '🧥',
    color_index: 0, size: 'XS', qty: 1,
    subtotal: 3400, delivery_price: 600, discount: 0, promo_code: null, total: 4000,
    notes: "المقاس لم يناسب", items: null, stock_deducted: false, created_at: new Date(Date.now() - 432000000).toISOString(), updated_at: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: 'demo-8', order_num: 'IH-449017', status: 'cancelled',
    customer_name: 'إيناس ربيع', phone: '0661445566',
    wilaya: 'الجلفة', commune: 'الجلفة', address: 'حي الشهداء',
    delivery_type: 'office', product_id: 5,
    product_name: 'فولار جيرسي فخم — بريميوم', product_emoji: '🧣',
    color_index: 0, size: 'M', qty: 2,
    subtotal: 4400, delivery_price: 400, discount: 0, promo_code: null, total: 4800,
    notes: null, items: null, stock_deducted: false, created_at: new Date(Date.now() - 518400000).toISOString(), updated_at: new Date(Date.now() - 432000000).toISOString(),
  },
];
